/** Site-wide links and metadata. */
export const site = {
  name: 'Youssef Taha',
  fullName: 'Youssef Taha Badawi',
  title: 'AI Engineer & GenAI Developer',
  tagline: 'Building Intelligent Systems with LLMs, RAG & Agentic AI',
  bio: 'GenAI Developer and AI Engineer with strong hands-on experience designing and delivering end-to-end Generative AI systems. Specialized in LLMs, Retrieval-Augmented Generation (RAG) pipelines, and Agentic AI architectures. Passionate about turning complex AI research into production-ready applications that solve real-world problems.',
  url: 'https://youssef-taha.netlify.app',
  email: 'ytaha8586@gmail.com',
  mailto: 'mailto:ytaha8586@gmail.com',
  phone: '+201066965772',
  phoneTel: 'tel:+201066965772',
  location: 'Cairo, Egypt',
  github: 'https://github.com/Youssefx64',
  linkedin: 'https://www.linkedin.com/in/yousseftahaai/',
  kaggle: 'https://www.kaggle.com/yousseftaha98',
  huggingface: 'https://huggingface.co/yousseftaha98',
  leetcode: 'https://leetcode.com/u/Youssef_Taha1/',
  youtube: 'https://www.youtube.com/@SirYoussefx64',
  googleScholar: '#',
  resumePdfPath: '#',
  avatarPath: '/avatar.png',
} as const;
